const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Mouse.Cnds.OnClick
	];
};
self.C3_JsPropNameTable = [
	{Fundo: 0},
	{Sólido: 0},
	{esquerdo: 0},
	{Meio: 0},
	{direito: 0},
	{começoDir: 0},
	{comoçoesq: 0},
	{Sprite7: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{lava: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{jogador: 0},
	{correndo: 0},
	{Teclado: 0},
	{Sprite: 0},
	{aparecendo: 0},
	{Sprite2: 0},
	{Senóide: 0},
	{Sprite3: 0},
	{cristal: 0},
	{passar: 0},
	{Sprite6: 0},
	{esqueletocava: 0},
	{Áudio: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{escuro: 0},
	{Fixar: 0},
	{Sprite18: 0},
	{Sprite20: 0},
	{Mouse: 0},
	{over: 0},
	{fim: 0},
	{estatuafim: 0},
	{Sprite19: 0},
	{Âncora: 0},
	{coracao: 0},
	{vidas: 0}
];

self.InstanceType = {
	Fundo: class extends self.ISpriteInstance {},
	esquerdo: class extends self.ISpriteInstance {},
	Meio: class extends self.ISpriteInstance {},
	direito: class extends self.ISpriteInstance {},
	começoDir: class extends self.ISpriteInstance {},
	comoçoesq: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	correndo: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	cristal: class extends self.ISpriteInstance {},
	passar: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	esqueletocava: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	escuro: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	over: class extends self.ISpriteInstance {},
	fim: class extends self.ISpriteInstance {},
	estatuafim: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	coracao: class extends self.ISpriteInstance {}
}